spring.application.name=AI-Powered-Interview-PreparationPlatform
spring.datasource.url=jdbc:mysql://localhost:3306/ai-pipp
spring.datasource.username=root
spring.datasource.password=Archana@123#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-3.5-flash
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true